modified:   .github/workflows/createPackage.yml #	modified:   scripts/fetch-latest-release.ps1

diff --git a/.github/workflows/createPackage.yml b/.github/workflows/createPackage.yml
--- a/.github/workflows/createPackage.yml
+++ b/.github/workflows/createPackage.yml
@@ -10,8 +10,18 @@ jobs:
     - name: Checkout code
       uses: actions/checkout@v2
 
-    - name: Install Chocolatey
-      run: Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
+    - name: Check for Chocolatey
+      run: |
+        if (-not (Get-Command choco -ErrorAction SilentlyContinue)) {
+          Write-Host "Chocolatey is not installed. Installing now..."
+          Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
+          
+          # Verify installation
+          if (-not (Get-Command choco -ErrorAction SilentlyContinue)) {
+            Write-Error "Failed to install Chocolatey. Aborting."
+            exit 1
+          }
+        }
       shell: pwsh
 
     - name: Validate Directory Structure and Files
