Update create-packages-from-github-release.yml

diff --git a/.github/workflows/create-packages-from-github-release.yml b/.github/workflows/create-packages-from-github-release.yml
--- a/.github/workflows/create-packages-from-github-release.yml
+++ b/.github/workflows/create-packages-from-github-release.yml
@@ -138,6 +138,6 @@ jobs:
             # Loop through the PRs to be merged and attempt to merge each into the default branch
             for pr in "${pr_array[@]}"; do
               echo "Debug: Attempting to merge PR #($pr) into the default branch."
-              gh pr merge $pr --auto --squash
+              gh pr merge $pr --squash --auto || echo "Failed to merge PR #$pr"
             done
         shell: bash
