Update create-packages-from-github-release.yml

diff --git a/.github/workflows/create-packages-from-github-release.yml b/.github/workflows/create-packages-from-github-release.yml
--- a/.github/workflows/create-packages-from-github-release.yml
+++ b/.github/workflows/create-packages-from-github-release.yml
@@ -74,12 +74,11 @@ jobs:
 
 
         # If an existing pull request is found, close it
-        if [[ ! -z "$existing_prs" ]]; then
-          pr_number=$(echo "$existing_prs" | awk '{print $1}')
-          echo "Closing PR #$pr_number"
+        IFS=$'\n' read -ra prs <<< "$existing_prs"
+        for pr_line in "${prs[@]}"; do
+          pr_number=$(echo "$pr_line" | awk '{print $1}')
           gh pr close "$pr_number" --comment "Closing PR as a new PR has been created for the same branch."
-          echo "Closed PR #$pr_number"
-        fi
+        done        
 
         # Commit and push changes
         echo "Committing and pushing changes to branch $unique_branch"
@@ -117,47 +116,34 @@ jobs:
           echo "Listing all open PRs:"
           gh pr list --state open
   
-          # Fetch PR numbers for specific label
-          pr_list_label=$(gh pr list --state open --label "auto gh-package")
-          # Convert to array
+          # Fetch PR numbers for specific label and convert to array
           echo "Listing all PRs matching the label (auto gh-package):"
-          pr_array_label=($pr_list_label)
-          for pr in "${pr_array_label[@]}"; do
-            gh pr view $pr
-          done
-          
+          pr_list_label=$(gh pr list --state open --label "auto gh-package" | awk '{print $1}')
+          IFS=' ' read -ra pr_array_label <<< "$pr_list_label"
 
-          # Fetch PR numbers for author
-          pr_list_author=$(gh pr list --state open --author "github-actions")
-          # Convert to array
+          # Fetch PR numbers for specific author and convert to array
           echo "Listing all PRs created by github-actions:"
-          pr_array_author=($pr_list_author)
-          for pr in "${pr_array_author[@]}"; do
-            gh pr view $pr
-          done
+          pr_list_author=$(gh pr list --state open --author "github-actions" | awk '{print $1}')
+          IFS=' ' read -ra pr_array_author <<< "$pr_list_author"
 
-          # Fetch PR numbers for author
-          pr_list_author2=$(gh pr list --state open --author "github-actions[bot]")
-          # Convert to array
+          # Fetch PR numbers for specific author (bot) and convert to array
           echo "Listing all PRs created by github-actions[bot]:"
-          pr_array_author2=($pr_list_author2)
-          for pr in "${pr_array_author2[@]}"; do
-            gh pr view $pr
-          done
+          pr_list_author2=$(gh pr list --state open --author "github-actions[bot]" | awk '{print $1}')
+          IFS=' ' read -ra pr_array_author2 <<< "$pr_list_author2"
 
-          # List all found PRs matching label
+          # Identify PRs that match both the label and the author
           echo "Listing all PRs matching both the label and author:"
           pr_array=()
           for pr in "${pr_array_label[@]}"; do
-            if [[ " ${pr_array_author[@]} " =~ " ${pr} " ]]; then
-              pr_array+=($pr)
-              gh pr view $pr
-            fi
+              if [[ " ${pr_array_author[@]} " =~ " ${pr} " ]] || [[ " ${pr_array_author2[@]} " =~ " ${pr} " ]]; then
+                  pr_array+=($pr)
+                  echo "Matched PR Number: $pr"
+              fi
           done
-  
-          # Loop through PR numbers and attempt to merge each
+
+          # Loop through the matched PR numbers and attempt to merge each
           for pr in "${pr_array[@]}"; do
-            gh pr merge $pr --merge --auto || echo "Failed to merge PR #$pr"
+              gh pr merge $pr --merge --auto || echo "Failed to merge PR #$pr"
           done
   
         shell: bash
